from .CityTown import *
from .Country import *
from .EmailConfig import *
from .Languages import *
from .Nationality import *
from .Organization import *
from .Occupation import *
from .Relationship import *
from .Religion import *
from .SmsConfig import *
from .State import *
from .Hobby import *
from .EmailCredentials import *
from .Sms_Credentials import *
from .Email_Queue import *
from .Sms_Queue import *
from .ClubInfo import *
from .District import *
from .Caste import *

